export const rhymingPairs = [
  "Melody of Dreams",
  "Riddles of the Wind",
  "Fantasy of Words",
  "Shadow of History",
  "Whisper of Fate",
  "Song of Life",
  "Rose of the Way",
  "Legend of Time",
  "Dawn of Dreams",
  "Whirlwind of Legends",
  "Light of Destiny",
  "Tablets of Wisdom",
  "The Way of the Wise",
  "Totem of Dreams",
  "Shadows of Words",
  "Rhythms of Destiny",
  "Fire of Words",
  "Dance of Shadows",
  "Solar Winds",
  "Chronicle of Memory",
  "Forest Magic",
  "Time of Shadows",
  "The Amazing Path",
  "Riddles of Words",
  "Melody of Paths",
  "Ideas of Wisdom",
  "Harmony of Time",
  "Color of Destiny",
  "Songs of Wisdom",
  "Magic of the Path",
  "Tablets of Dreams",
  "Path of Dreams",
  "Magic Dreams",
  "Legend of Dreams",
  "Networks of Time",
  "Magic of Stories",
  "Epic of Wisdom",
  "Melody of Wisdom",
  "Light of Shadows",
  "Riddles of Time",
  "Midnight Sun",
  "Totem of Wisdom",
  "Thunder of Dreams",
  "Path of Time",
  "Look of Wisdom",
  "Winds of Legends",
  "Decision of Shadows",
  "Time of Fate",
  "Dream of Wisdom",
  "Dance of Dreams",
  "Magic of Words",
  "Iron of Dreams",
  "Fire of Legends",
  "Epic of Shadows",
  "Thunderstorm of Wisdom",
  "The Way of Fantasy",
  "The Light of Totems",
  "The Legend of Shadows",
  "The Riddle of Fate",
  "The Dance of Melodies",
  "The Way of Songs",
  "The Magic of Dreams",
  "The Miracle of Wisdom",
  "The Wind of Fate",
  "Dance of Silver",
  "Light of Songs",
  "Melody of History",
  "Path of Memories",
  "Magic Fire",
  "Amazing Legend",
  "Fire of Wisdom",
  "Magic of the Sun",
  "Dance of Dreams",
];
